/**
 * P1.10 loader: data/processed + pipeline/data (hand-curated YAML) → Postgres (Neon).
 *
 * One transaction per budget version: delete that version's rows, insert everything fresh.
 * Re-running is safe, and a failure part-way leaves the database exactly as it was.
 * Numbers are copied, never computed. Embeddings are left NULL (need a Voyage key; see
 * docs/open-questions.md) — the full-text `tsv` columns are generated by Postgres.
 *
 * Run: pnpm db:load
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { config } from 'dotenv'
import { eq } from 'drizzle-orm'
import { drizzle } from 'drizzle-orm/node-postgres'
import { asyncBufferFromFile, parquetReadObjects } from 'hyparquet'
import { Pool } from 'pg'
import YAML from 'yaml'

import * as s from '../lib/db/schema'

config({ path: '.env.local' })

const ROOT = process.cwd()
const PROCESSED = join(ROOT, 'data', 'processed')
const CURATED = join(ROOT, 'pipeline', 'data')
const VERSION = {
  slug: '2027-proposed-3rd-run-2026-09-14',
  fiscalYear: 2027,
  stage: 'proposed' as const,
  runLabel: '3rd Run 9/14/26',
}

type Row = Record<string, unknown>

/** parquet INT64 → BigInt; every value here is far below 2^53, so plain numbers are exact. */
function plain(v: unknown): unknown {
  if (typeof v === 'bigint') return Number(v)
  if (Array.isArray(v)) return v.map(plain)
  if (v && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, plain(x)]))
  return v
}

async function parquet(name: string): Promise<Row[]> {
  const file = await asyncBufferFromFile(join(PROCESSED, `${name}.parquet`))
  return ((await parquetReadObjects({ file })) as Row[]).map((r) => plain(r) as Row)
}

const yaml = (name: string) => YAML.parse(readFileSync(join(CURATED, name), 'utf8')) as Row[]
const json = (name: string) => JSON.parse(readFileSync(join(PROCESSED, name), 'utf8'))
const jsonl = (name: string) =>
  readFileSync(join(PROCESSED, name), 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l) as Row)

/** numeric columns take strings (exact); blank stays null, never 0. */
const dec = (v: unknown): string | null => (v === null || v === undefined || v === '' ? null : String(v))
const int = (v: unknown): number | null => (v === null || v === undefined || v === '' ? null : Number(v))
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : [])

async function insertAll<T extends Row>(tx: Tx, table: Parameters<Tx['insert']>[0], rows: T[], size = 500) {
  for (let i = 0; i < rows.length; i += size) await tx.insert(table).values(rows.slice(i, i + size) as never)
}

type Db = ReturnType<typeof drizzle<typeof s>>
type Tx = Parameters<Parameters<Db['transaction']>[0]>[0]

const CHILD_TABLES = [
  s.chunks, s.concepts, s.positionLines, s.lineItems, s.revenues, s.capitalProjects, s.positionChanges,
  s.kpis, s.services, s.deptSummary, s.fteSummary, s.positionsSummary, s.sectionComparisons,
  s.sectionTotals, s.deptCrosswalk, s.glossary, s.fees, s.budgetFacts, s.departments, s.documents,
] as const

async function load(db: Db) {
  const [
    lineItems, positionLines, sectionTotals, sectionComparisons, positionsSummary, fteSummary,
    deptSummary, services, kpis, positionChanges, capitalProjects, revenues, concepts,
  ] = await Promise.all(
    ['line_items', 'position_lines', 'section_totals', 'section_comparisons', 'positions_summary', 'fte_summary',
      'dept_summary', 'services', 'kpis', 'position_changes', 'capital_projects', 'revenues', 'concepts'].map(parquet),
  )
  const departments = yaml('departments.yaml')
  const crosswalk = json('dept_crosswalk.json') as Row[]
  const chunks = jsonl('chunks.jsonl')

  return db.transaction(async (tx) => {
    // budget version: find or create, then clear its rows (children before parents)
    const existing = await tx.select().from(s.budgetVersions).where(eq(s.budgetVersions.slug, VERSION.slug))
    const versionId = existing[0]?.id ??
      (await tx.insert(s.budgetVersions).values(VERSION).returning({ id: s.budgetVersions.id }))[0].id
    for (const t of CHILD_TABLES) await tx.delete(t).where(eq(t.budgetVersionId, versionId))
    const v = { budgetVersionId: versionId }

    const docs = await tx.insert(s.documents).values([
      { ...v, kind: 'summary', title: '2027 Proposed Plan and Executive Budget Summary',
        filePath: 'data/raw/2027-Proposed-Plan-and-Executive-Budget-Summary.pdf', pageOffset: 10 },
      { ...v, kind: 'detailed', title: '2027 Proposed Detailed Budget',
        filePath: 'data/raw/2027-Proposed-Detailed-Budget.pdf', pageOffset: 0 },
    ]).returning({ id: s.documents.id, kind: s.documents.kind })
    const docId = Object.fromEntries(docs.map((d) => [d.kind, d.id]))

    // departments, then parents (DPW divisions → dpw)
    const depts = await tx.insert(s.departments).values(departments.map((d) => ({
      ...v, slug: String(d.slug), name: String(d.name), shortName: (d.short_name as string) ?? null,
      section: String(d.section), aliases: arr(d.aliases),
    }))).returning({ id: s.departments.id, slug: s.departments.slug })
    const dept = Object.fromEntries(depts.map((d) => [d.slug, d.id])) as Record<string, number>
    for (const d of departments.filter((d) => d.parent)) {
      await tx.update(s.departments).set({ parentId: dept[String(d.parent)] }).where(eq(s.departments.id, dept[String(d.slug)]))
    }
    const deptOf = (slug: unknown) => (slug ? dept[String(slug)] ?? null : null)
    const sectionDept: Record<string, number> = {}
    for (const d of departments) for (const p of arr(d.detailed)) sectionDept[p] = dept[String(d.slug)]

    await insertAll(tx, s.deptCrosswalk, crosswalk.filter((c) => c.summary_pdf_pages).map((c) => {
      const pages = c.summary_pdf_pages as number[]
      return { ...v, deptId: dept[String(c.dept)], summaryPdfPageStart: pages[0], summaryPdfPageEnd: pages[1],
        detailedPagePrefix: arr(c.detailed_page_prefix).join(',') || null, orgCodes: arr(c.org_codes), fundCodes: arr(c.fund_codes) }
    }))

    await insertAll(tx, s.sectionTotals, sectionTotals.map((r) => ({ ...v, section: String(r.section), label: String(r.label),
      line: r.line as 'budget', adopted2026: int(r.adopted_2026), proposed2027: int(r.proposed_2027), change: int(r.change),
      taxRate2026: dec(r.tax_rate_2026), taxRate2027: dec(r.tax_rate_2027), taxRateChange: dec(r.tax_rate_change), cite: r.cite as s.Cite })))
    await insertAll(tx, s.sectionComparisons, sectionComparisons.map((r) => ({ ...v, section: String(r.section),
      groupPath: arr(r.group_path), line: String(r.line), adopted2026: int(r.adopted_2026), requested2027: int(r.requested_2027),
      proposed2027: int(r.proposed_2027), changeVsAdopted: int(r.change_vs_adopted), changeVsRequested: int(r.change_vs_requested),
      cite: r.cite as s.Cite })))
    await insertAll(tx, s.positionsSummary, positionsSummary.map((r) => ({ ...v, label: String(r.label),
      groupName: (r.group as string) ?? null, isDivisionSubtotal: Boolean(r.is_division_subtotal),
      adopted2026: int(r.adopted_2026), requested2027: int(r.requested_2027), proposed2027: int(r.proposed_2027),
      changeVsAdopted: int(r.change_vs_adopted), changeVsRequested: int(r.change_vs_requested), cite: r.cite as s.Cite })))
    await insertAll(tx, s.fteSummary, fteSummary.map((r) => ({ ...v, funding: r.funding as 'om', label: String(r.label),
      groupName: (r.group as string) ?? null, isDivisionSubtotal: Boolean(r.is_division_subtotal),
      adopted2026: dec(r.adopted_2026), requested2027: dec(r.requested_2027), proposed2027: dec(r.proposed_2027),
      changeVsAdopted: dec(r.change_vs_adopted), changeVsRequested: dec(r.change_vs_requested), cite: r.cite as s.Cite })))

    await insertAll(tx, s.deptSummary, deptSummary.map((r) => ({ ...v, deptId: dept[String(r.dept)], metric: String(r.metric),
      label: String(r.label), groupName: (r.group as string) ?? null, actual2025: dec(r.actual_2025), adopted2026: dec(r.adopted_2026),
      requested2027: dec(r.requested_2027), proposed2027: dec(r.proposed_2027), changeVsAdopted: dec(r.change_vs_adopted),
      changeVsRequested: dec(r.change_vs_requested), flags: arr(r.flags), labelWrapped: Boolean(r.label_wrapped), cite: r.cite as s.Cite })))
    await insertAll(tx, s.services, services.map((r) => ({ ...v, deptId: dept[String(r.dept)], description: String(r.description),
      operating: int(r.operating), capital: int(r.capital), grant: int(r.grant), ftes: dec(r.ftes), isTotal: Boolean(r.is_total),
      cite: r.cite as s.Cite })))
    await insertAll(tx, s.kpis, kpis.map((r) => ({ ...v, deptId: dept[String(r.dept)], measure: String(r.measure),
      groupName: (r.group as string) ?? null, colLabels: arr(r.col_labels), values: arr(r.values), footnote: (r.footnote as string) ?? null,
      flags: arr(r.flags), cite: r.cite as s.Cite })))
    await insertAll(tx, s.positionChanges, positionChanges.map((r) => ({ ...v, deptId: dept[String(r.dept)], positions: dec(r.positions),
      omFtes: dec(r.om_ftes), nonOmFtes: dec(r.non_om_ftes), title: String(r.title), section: (r.section as string) ?? null,
      groupName: (r.group as string) ?? null, reason: (r.reason as string) ?? null,
      reasonCategory: (r.reason_category as 'other') ?? null, isTotal: Boolean(r.is_total),
      mergedWithPrevious: Boolean(r.merged_with_previous), cite: r.cite as s.Cite })))
    await insertAll(tx, s.capitalProjects, capitalProjects.map((r) => ({ ...v, deptId: deptOf(r.dept), name: (r.name as string) ?? null,
      amount: int(r.amount), amountText: (r.amount_text as string) ?? null, amountFromMillions: Boolean(r.amount_from_millions),
      description: (r.description as string) ?? null, pdfPages: (r.pdf_pages as number[]) ?? [], cite: r.cite as s.Cite })))

    // line items → keep ids so position lines can point at their line
    const liIds: Record<string, number> = {}
    for (let i = 0; i < lineItems.length; i += 500) {
      const chunk = lineItems.slice(i, i + 500)
      const ids = await tx.insert(s.lineItems).values(chunk.map((r) => ({ ...v, deptId: sectionDept[String(r.section)] ?? null,
        section: String(r.section), rowType: String(r.row_type), block: (r.block as 'decision_unit') ?? null,
        fund: (r.fund as string) ?? null, org: (r.org as string) ?? null, sbcl: (r.sbcl as string) ?? null,
        account: (r.account as string) ?? null, category: (r.category as string) ?? null, hierarchyPath: arr(r.hierarchy_path),
        description: String(r.description), descriptionRaw: String(r.description_raw), payRange: (r.pay_range as string) ?? null,
        actual2025: int(r.actual_2025), adopted2026Units: dec(r.adopted_2026_units), adopted2026: int(r.adopted_2026),
        requested2027Units: dec(r.requested_2027_units), requested2027: int(r.requested_2027),
        proposed2027Units: dec(r.proposed_2027_units), proposed2027: int(r.proposed_2027),
        isSubtotal: Boolean(r.is_subtotal), isUnitTotal: Boolean(r.is_unit_total), isPosition: Boolean(r.is_position),
        isDeduction: Boolean(r.is_deduction), footnoteFlag: Boolean(r.footnote_flag), footnoteCodes: arr(r.footnote_codes),
        flags: arr(r.flags), note: (r.note as string) ?? null, cite: r.cite as s.Cite })))
        .returning({ id: s.lineItems.id })
      chunk.forEach((r, j) => { liIds[`${r.pdf_page}:${r.line_no}`] = ids[j].id })
    }
    await insertAll(tx, s.positionLines, positionLines.map((r) => ({ ...v, lineItemId: liIds[`${r.pdf_page}:${r.line_no}`] ?? null,
      deptId: sectionDept[String(r.section)] ?? null, title: String(r.title), footnoteCodes: arr(r.footnote_codes),
      payRange: (r.pay_range as string) ?? null, hierarchyPath: arr(r.hierarchy_path),
      adopted2026Units: dec(r.adopted_2026_units), adopted2026: int(r.adopted_2026),
      requested2027Units: dec(r.requested_2027_units), requested2027: int(r.requested_2027),
      proposed2027Units: dec(r.proposed_2027_units), proposed2027: int(r.proposed_2027), cite: r.cite as s.Cite })))

    await insertAll(tx, s.revenues, revenues.map((r) => ({ ...v, source: r.source as 'summary', isTotal: Boolean(r.is_total),
      account: (r.account as string) ?? null, fund: (r.fund as string) ?? null, deptId: deptOf(r.dept),
      category: (r.category as string) ?? null, line: String(r.line), actual2025: int(r.actual_2025), adopted2026: int(r.adopted_2026),
      requested2027: int(r.requested_2027), proposed2027: int(r.proposed_2027), cite: r.cite as s.Cite })))

    await insertAll(tx, s.glossary, yaml('glossary.yaml').map((g) => ({ ...v, term: String(g.term), plainDefinition: String(g.plain_definition),
      whyItMatters: (g.why_it_matters as string) ?? null, citeText: (g.cite_text as string) ?? null, aliases: arr(g.aliases),
      definitionSource: (g.definition_source as string) ?? null, alsoCite: g.also_cite ?? null, reviewedBy: (g.reviewed_by as string) ?? null,
      cite: g.cite as s.Cite })))
    await insertAll(tx, s.fees, yaml('fees.yaml').map((f) => ({ ...v, fee: String(f.fee), unit: String(f.unit),
      value2026: dec(f.value_2026), value2027: dec(f.value_2027), pctChange: dec(f.pct_change_printed), revenue2027: int(f.revenue_2027),
      isDerived: Boolean(f.is_derived), sourceText: (f.source_text as string) ?? null,
      narrativeRevenue: (f.narrative_revenue as string) ?? null, reviewedBy: (f.reviewed_by as string) ?? null, cite: f.cite as s.Cite })))
    await insertAll(tx, s.budgetFacts, yaml('budget_facts.yaml').map((f) => ({ ...v, id: String(f.id), topic: String(f.topic),
      statement: String(f.statement), value: dec(f.value), unit: (f.unit as string) ?? null, reviewedBy: (f.reviewed_by as string) ?? null,
      leadWith: (f.lead_with as string) ?? null, context: (f.context as string) ?? null, tablePair: f.table_pair ?? null,
      alsoCite: f.also_cite ?? null, cite: f.cite as s.Cite })))

    await insertAll(tx, s.concepts, concepts.map((c) => ({ ...v, kind: c.kind as 'account', label: String(c.label),
      code: (c.code as string) ?? null, deptIds: arr(c.dept_ids).map((d) => dept[d]).filter(Boolean),
      occurrences: int(c.occurrences), gloss: (c.gloss as string) ?? null, glossReviewed: Boolean(c.gloss_reviewed) })))
    await insertAll(tx, s.chunks, chunks.map((c) => ({ ...v, id: String(c.id), docId: docId[String(c.doc)] ?? null, deptId: deptOf(c.dept),
      region: (c.region as string) ?? null, kind: (c.kind as 'narrative') ?? 'narrative', sectionType: String(c.section_type),
      heading: (c.heading as string) ?? null, ordinal: int(c.ordinal), text: String(c.text), contextHeader: String(c.context_header),
      pdfPage: Number(c.pdf_page), pageEnd: int(c.page_end), printedPage: String(c.printed_page),
      parentSectionId: (c.parent_section_id as string) ?? null, linkedTables: arr(c.linked_tables) })), 200)

    return {
      budget_version_id: versionId, departments: depts.length, line_items: lineItems.length, position_lines: positionLines.length,
      dept_summary: deptSummary.length, services: services.length, kpis: kpis.length, position_changes: positionChanges.length,
      capital_projects: capitalProjects.length, revenues: revenues.length, section_totals: sectionTotals.length,
      section_comparisons: sectionComparisons.length, positions_summary: positionsSummary.length, fte_summary: fteSummary.length,
      concepts: concepts.length, chunks: chunks.length,
    }
  })
}

async function main() {
  const url = process.env.DATABASE_URL
  if (!url) throw new Error('DATABASE_URL is not set (.env.local)')
  const pool = new Pool({ connectionString: url, max: 1 })
  try {
    const counts = await load(drizzle(pool, { schema: s }))
    process.stdout.write(`${JSON.stringify(counts, null, 2)}\n`)
  } catch (err) {
    // drizzle's message echoes the whole query; the database's reason is on `cause`
    const cause = (err as { cause?: { message?: string; detail?: string } }).cause
    const reason = cause?.message ? `${cause.message}${cause.detail ? ` — ${cause.detail}` : ''}` : String(err).slice(0, 300)
    process.stderr.write(`load failed — nothing was changed (transaction rolled back): ${reason}\n`)
    process.exitCode = 1
  } finally {
    await pool.end()
  }
}

void main()
